### ISSUE TITLE
running into an issue with pkonfound

### ISSUE THREAD

**Issue by jrosen48** [jrosen48/konfound#22]
@linqinyu any idea what may be causing this? I *think* the other functions are working okay, and wonder if a) a change to any existing functions (this seems most likely?!?) or b) adding `tkonfound()` might have caused this?

``` r
library(konfound)
#> Sensitivity analysis as described in Frank, Maroulis, Duong, and Kelcey (2013) and in Frank (2000).
#> For more information visit http://konfound-it.com.
nl_output <- pkonfound(-0.2, 0.103, 20888, 3, n_trm = 17888, non_linear = TRUE)
#> Error in isTRUE(tryall_t - thr_t > 0 & tryall_est * est > 0): object 'est' not found
nl_output
```

<sup>Created on 2020-04-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by linqinyu** [comment]
I am checking this now!

**Comment by jrosen48** [comment]
sa-weet!

**Comment by linqinyu** [comment]
I think I fixed it but have not tested it yet! Just commit the fix and let me know if it works? Thx!!

**Comment by jrosen48** [comment]
awesome, running it right now! talk about fast development! :)

**Comment by jrosen48** [comment]
did it! Thank you!
